### ISSUE TITLE
Update dymension RDK repo README

### ISSUE THREAD

**Issue by omritoptix** [dymensionxyz/RDK#123]
We need to add more info on the README.md about the RDK.
Currently it's the readme forked from cosmos-sdk.

**Comment by yishay-dym** [comment]
@mtsitrin please update my version readme.md to be dev compatible.

**Comment by shaolin-flow** [comment]
Required for testnet. The README will include the product vision for the RDK and timeline.

**Comment by mtsitrin** [comment]
Under discussion at https://github.com/dymensionxyz/research/discussions/52
