### ISSUE TITLE
Distribution module to distribute rewards in a rollapp

### ISSUE THREAD

**Issue by mtsitrin** [dymensionxyz/RDK#149]
## Summary

The distribution module should distribute the rewards as follows:

- predefined percentage to the community pool
- predefined percentage to the sequencer
- Future feature: the reminder to be distributed according to some applicative voting power

## Problem Definition

Currently the distribution doesn't work as it's coupled with tendermint and tries to distriubte according to the validators signing the block (part of tendermint consensus)

## Proposal

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by shaolin-flow** [comment]
Is this blocking for testnet with one validator?

**Comment by mtsitrin** [comment]
It's the required functionality for distributing to the proposer.
Without all fees goes to community pool
