### ISSUE TITLE
RDK upstream with v0.46.x

### ISSUE THREAD

**Issue by shaolin-flow** [dymensionxyz/RDK#152]

**Comment by mtsitrin** [comment]
@shaolin-flow when RDK is on v0.46.x but the settlement is v0.45.x we get the following issue:
https://github.com/dymensionxyz/dymint/issues/161

I think we need to upgrade the hub to v0.46.6

**Comment by mtsitrin** [comment]
Another issue is that CosmWasm doesn't support v0.46.x yet (https://docs.cosmwasm.com/docs/1.0/integration/#prerequisites)

**Comment by shaolin-flow** [comment]
Hold upstreaming RDK to Cosmos SDK V46.x for the foreseeable future.

**Comment by shaolin-flow** [comment]
Upgrade to the latest stable version in v45.X, we will upstream to v46 for incentivized testnet.
