### ISSUE TITLE
review globalfee and txfees modules

### ISSUE THREAD

**Issue by mtsitrin** [dymensionxyz/RDK#153]
Review the following modules, decide whether relevant to the rollapp use case

https://github.com/cosmos/gaia/blob/main/docs/modules/globalfee.md
https://github.com/osmosis-labs/osmosis/tree/main/x/txfees

**Comment by mtsitrin** [comment]
@shaolin-flow 
Current method for minimum supported fees is by defining "min_gas_prices" at validator's node.

Regarding GlobalFee module:
* Allows to have "global" fees requirement, across all validator nodes
* The "min_gas_prices" of the validator can have "harder" requirement

Regarding txfees module:
* As above, allows to set multiple tokens for fees. Globally validated.
* Different from above, the fees paid are swapped to the base denom



IMO, those modules are not required for a rollapp:
* We'll have single/few sequencers. Not sure the GlobalFee validation is required. fees can be enforced using sequencer's  "min_gas_prices" param


let me know what u think

**Comment by shaolin-flow** [comment]
Agreed these are not required for the RDK. As such, closing this issue.
