### ISSUE TITLE
Limit the staking "create validator" for testnet

### ISSUE THREAD

**Issue by mtsitrin** [dymensionxyz/RDK#158]
We want to have hard limit of single validator which is the sequencer.

Validator creation in a rollapp will be disabled for now

**Comment by shaolin-flow** [comment]
Why do we need to change the RDK for this if we can limit who can post state transitions on the Dymension Hub?

**Comment by mtsitrin** [comment]
Because having single set of validators that contains both the sequencer and on-chain created validators can lead to undefined behaviour.

I think this functionality should be enabled as discussed in ADR#2.

Anyway, it's not mandatory.
